trigger:
- main

pool:
  name: 'Default'
  demands:
  - agent.name -equals windows_agent

variables:
  azureServiceConnection: 'Terraform'
  System.Debug: 'true'

resources:
  repositories:
    - repository: terraformRepo
      type: github
      name: nikita0150/Terraform_az
      endpoint: github.com_nikita0150

steps:

# Checkout Azure Repo (pipeline YAML location)
- checkout: self

# Checkout GitHub Repo (Terraform code)
- checkout: terraformRepo
  path: terraform-code

# Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# Verify terraform executable on agent (helps debug ENOENT)
- task: PowerShell@2
  displayName: 'Verify terraform executable on agent'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Checking terraform path on agent"
      $p = 'C:\Users\Admin\Downloads\agent\_work\_tool\terraform\1.14.5\x64\terraform.exe'
      if (Test-Path $p) {
        Write-Host 'FOUND:' $p
        & $p -version
      } else {
        Write-Host 'NOT FOUND:' $p
        Write-Host 'Listing terraform tool cache (two levels):'
        Get-ChildItem 'C:\Users\Admin\Downloads\agent\_work\_tool\terraform' -Recurse -Depth 2 | Select-Object FullName, Mode, Length -First 50
      }
      Write-Host 'ICACLS output:'
      if (Test-Path $p) {
        icacls $p
      } else {
        Write-Host 'icacls failed or file missing'
      }

# Debug: run terraform init via explicit executable to capture spawn errors
- task: PowerShell@2
  displayName: 'Debug: run terraform init (direct)'
  inputs:
    targetType: 'inline'
    script: |
      $workDir = "$(Build.SourcesDirectory)\terraform-code\poc2"
      Write-Host "Working directory: $workDir"
      Push-Location $workDir
      try {
        $tf = (Get-Command terraform -ErrorAction SilentlyContinue)?.Source
        if (-not $tf) { $tf = 'C:\Users\Admin\Downloads\agent\_work\_tool\terraform\1.14.5\x64\terraform.exe' }
        Write-Host "Using terraform executable: $tf"
        if (-not (Test-Path $tf)) { throw "terraform executable not found at $tf" }

        $args = @(
          'init',
          '-backend-config=storage_account_name=storageacc235',
          '-backend-config=container_name=tfstate',
          '-backend-config=key=terraform.tfstate',
          '-backend-config=resource_group_name=tfstate-rg'
        )

        $maxAttempts = 2
        for ($i=1; $i -le $maxAttempts; $i++) {
          Write-Host "Attempt $i: running terraform $($args -join ' ')"
          try {
            $proc = Start-Process -FilePath $tf -ArgumentList $args -NoNewWindow -PassThru -Wait -ErrorAction Stop
            Write-Host "terraform exited with code $($proc.ExitCode)"
            if ($proc.ExitCode -eq 0) { break }
          } catch {
            Write-Host "Error invoking terraform: $_"
            if ($i -lt $maxAttempts) { Write-Host 'Retrying in 5s...'; Start-Sleep -Seconds 5 }
            else { throw }
          }
        }
      } finally {
        Pop-Location
      }

# Terraform Init
- task: TerraformTaskV4@4
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'terraform-code/poc2'
    backendServiceArm: '$(azureServiceConnection)'
    backendAzureRMResourceGroupName: 'tfstate-rg'
    backendAzureRMStorageAccountName: 'storageacc235'
    backendAzureRMContainerName: 'tfstate'
    backendAzureRMKey: 'terraform.tfstate'

# Terraform Plan
- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'terraform-code/poc2'
    environmentServiceNameAzureRM: '$(azureServiceConnection)'

# Terraform Apply
- task: TerraformTaskV4@4
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'terraform-code/poc2'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: '$(azureServiceConnection)'