trigger:
- main

pool:
  name: 'Default'
  demands:
  - agent.name -equals windows_agent

variables:
  azureServiceConnection: 'Terraform'
  workingDir: '$(System.DefaultWorkingDirectory)\poc2'
  System.Debug: 'true'

steps:

# Checkout current repo (main branch)
- checkout: self

- script: |
    echo Current directory:
    cd
    echo Listing repo root:
    dir
    echo Listing Terraform folder:
    dir "$(workingDir)"
  displayName: 'Verify Terraform Directory'

# Install Terraform
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'

# Terraform Init
- task: TerraformTaskV4@4
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(workingDir)'
    backendServiceArm: '$(azureServiceConnection)'
    backendAzureRMResourceGroupName: 'Panda_Prod'
    backendAzureRMStorageAccountName: 'storageacc235'
    backendAzureRMContainerName: 'tfstatefile'
    backendAzureRMKey: 'terraform.tfstate'

# Terraform Plan
- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(workingDir)'
    environmentServiceNameAzureRM: '$(azureServiceConnection)'

# Terraform Apply
- task: TerraformTaskV4@4
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve'
    workingDirectory: '$(workingDir)'
    environmentServiceNameAzureRM: '$(azureServiceConnection)'