trigger:
- main

pool:
  name: 'Default'

variables:
  workingDir: '$(System.DefaultWorkingDirectory)/hub_spoc_networking_project/env/dev'
  tfvarFile: '$(workingDir)/dev.tfvars'
steps:

- checkout: self

# Azure Login using Service Connection
- task: AzureCLI@2
  displayName: 'Azure Login'
  inputs:
    azureSubscription: 'Terraform'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Logged into Azure"

# Terraform Init
- script: |
    terraform init \
      -backend-config="resource_group_name=rg-tfstate" \
      -backend-config="storage_account_name=tfstatehubspoke34" \
      -backend-config="container_name=tfstatefile" \
      -backend-config="key=networking.tfstate" \
      -input=false -no-color
  displayName: 'Terraform Init'
  workingDirectory: '$(workingDir)'

# Terraform Validate
- script: |
    terraform validate
  displayName: 'Terraform Validate'
  workingDirectory: '$(workingDir)'

# Terraform Plan
- script: |
    terraform plan -out=tfplan -var-file="$(tfVarFile)" -input=false -no-color 

  displayName: 'Terraform Plan'
  workingDirectory: '$(workingDir)'