trigger:
- main

pool:
  name: 'Default'

variables:
  workingDir: '$(System.DefaultWorkingDirectory)/hub_spoc_networking_project/env/dev'
  tfvarFile: 'dev.tfvars'  # relative to workingDir

steps:

- checkout: self

# Terraform Init, Validate, Plan in one task with Azure login
- task: AzureCLI@2
  displayName: 'Terraform Init/Validate/Plan'
  inputs:
    azureSubscription: 'Terraform'   # your service connection
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: '$(workingDir)'
    inlineScript: |
      echo "Starting Terraform workflow"

      terraform init \
        -backend-config="resource_group_name=rg-tfstate" \
        -backend-config="storage_account_name=tfstatehubspoke34" \
        -backend-config="container_name=tfstatefile" \
        -backend-config="key=networking.tfstate" \
        -input=false -no-color

      terraform validate

      terraform plan -var-file="$(tfvarFile)" -out=tfplan -input=false -no-color