trigger:
- main
- dev

pool:
  name: 'Default'

variables:
  workingDir: '$(System.DefaultWorkingDirectory)/hub_spoc_networking_project/env'
  tfvarFile: 'dev.tfvars'   # default, will be overridden dynamically

steps:

- checkout: self

# Set TFVAR file dynamically based on branch
- script: |
    echo "Determining environment from branch name..."
    if [[ "$(Build.SourceBranchName)" == "main" ]]; then
      echo "Using prod.tfvars"
      echo "##vso[task.setvariable variable=tfvarFile]prod.tfvars"
    else
      echo "Using dev.tfvars"
      echo "##vso[task.setvariable variable=tfvarFile]dev.tfvars"
  displayName: 'Set TFVAR file dynamically'

# Azure login
- task: AzureCLI@2
  displayName: 'Azure Login'
  inputs:
    azureSubscription: 'Terraform'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Logged into Azure"

# Terraform Init
- task: AzureCLI@2
  displayName: 'Terraform Init'
  inputs:
    azureSubscription: 'Terraform'
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: '$(workingDir)/$(Build.SourceBranchName)'
    inlineScript: |
      terraform init \
        -backend-config="resource_group_name=rg-tfstate" \
        -backend-config="storage_account_name=tfstatehubspoke34" \
        -backend-config="container_name=tfstatefile" \
        -backend-config="key=networking.tfstate" \
        -input=false -no-color

# Terraform Validate
- task: AzureCLI@2
  displayName: 'Terraform Validate'
  inputs:
    azureSubscription: 'Terraform'
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: '$(workingDir)/$(Build.SourceBranchName)'
    inlineScript: |
      terraform validate

# Terraform Plan
- task: AzureCLI@2
  displayName: 'Terraform Plan'
  inputs:
    azureSubscription: 'Terraform'
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: '$(workingDir)/$(Build.SourceBranchName)'
    inlineScript: |
      terraform plan -var-file="$(tfvarFile)" -out=tfplan -input=false -no-color